### PR TITLE
updated codebase to flask 2.0 and mtaa 1.5 

### PR DESCRIPTION
**Pull request by Kalebu**
Hello , 

I have upgraded the codebase with the updated flask 2.0 route decorator feature and also upgraded the mtaa codebase to use the advantage of an upgrade in 1.5 to make it more readable together with supporting grouped locations

### CODE REVIEW

**Review by maotora — COMMENTED** [review]
Looks good to me. ✊🏿

**Comment by AnoRebel** [comment]
Great work man,thanks alot. I see you've cleaned up the pages too, i was lazy on that.
Keep up the help man, it's much appreciated.
Merging now..

**Comment by AnoRebel** [comment]
> Looks good to me. ✊🏿

Yeah, merging it now.

**Comment by AnoRebel** [comment]
> Hello ,
> 
> I have upgraded the codebase with the updated flask 2.0 route decorator feature and also upgraded the mtaa codebase to use the advantage of an upgrade in 1.5 to make it more readable together with supporting grouped locations

Great work man,thanks alot. I see you've cleaned up the pages too, i was lazy on that.
Keep up the help man, it's much appreciated.
Merging now..

**Comment by AnoRebel** [comment]
It seems we have a bug in deployment though.

> File "/app/wsgi.py", line 3, in <module>
2021-05-29T20:35:43.415946+00:00 app[web.1]: app = create_app()
2021-05-29T20:35:43.415947+00:00 app[web.1]: File "/app/api/__init__.py", line 15, in create_app
2021-05-29T20:35:43.415947+00:00 app[web.1]: from api.schema import schema
2021-05-29T20:35:43.415947+00:00 app[web.1]: File "/app/api/schema.py", line 24, in <module>
2021-05-29T20:35:43.415948+00:00 app[web.1]: class Tanzania(ObjectType):
2021-05-29T20:35:43.415948+00:00 app[web.1]: File "/app/api/schema.py", line 26, in Tanzania
2021-05-29T20:35:43.415948+00:00 app[web.1]: regions = list(tanzania)
2021-05-29T20:35:43.415949+00:00 app[web.1]: TypeError: 'Tanzania' object is not iterable

These are the heroku logs, so the error is there (line 26), i'll check it out when i get the time.

**Comment by Kalebu** [comment]
Update the requirements.txt to flask 2.0 and mtaa 1.5

**Pull request merged**
